namespace Plutonium.Agent.BotSystem.Entities;

public enum ENET_PACKET_FLAG
{
    PACKET_FLAG_NONE = 0,
    PACKET_FLAG_UNK = 1 << 1,
    PACKET_FLAG_RESET_VISUAL_STATE = 1 << 2, // 4
    PACKET_FLAG_EXTENDED = 1 << 3, // 8
    PACKET_FLAG_ROTATE_LEFT = 1 << 4, // 16
    PACKET_FLAG_ON_SOLID = 1 << 5, // 32
    PACKET_FLAG_ON_FIRE_DAMAGE = 1 << 6, // 64
    PACKET_FLAG_ON_JUMP = 1 << 7, // 128
    PACKET_FLAG_ON_KILLED = 1 << 8, // 256
    PACKET_FLAG_ON_PUNCHED = 1 << 9, // 512
    PACKET_FLAG_ON_PLACED = 1 << 10, // 1024
    PACKET_FLAG_ON_TILE_ACTION = 1 << 11, // 2048
    PACKET_FLAG_ON_GOT_PUNCHED = 1 << 12, // 4096
    PACKET_FLAG_ON_RESPAWNED = 1 << 13, // 8192
    PACKET_FLAG_ON_COLLECT_OBJECT = 1 << 14, // 16384
    PACKET_FLAG_ON_TRAMPOLINE = 1 << 15, // 32768
    PACKET_FLAG_ON_DAMAGE = 1 << 16, // 65536
    PACKET_FLAG_ON_SLIDE = 1 << 17, // 131072
    PACKET_FLAG_ON_WALL_HANG = 1 << 21, // 2097152
    PACKET_FLAG_ON_ACID_DAMAGE = 1 << 26, // 67108864
    PACKET_FLAG_MAX = 31
}

public enum ENET_PLAYER_STATE
{
    UPDATE_PACKET_FALLING_DOWN = 0,
    UPDATE_PACKET_TILE_CHANGE_REQUEST_RIGHT = 0,
    UPDATE_PACKET_TILE_CHANGE_REQUEST_LEFT = 16,
    UPDATE_PACKET_PLAYER_MOVING_RIGHT = 32, //higher tile pos
    UPDATE_PACKET_PLAYER_MOVING_LEFT = 48, //lower tile pos
    UPDATE_PACKET_PLAYER_JUMPING_RIGHT = 128, //higher tile pos
    UPDATE_PACKET_PLAYER_JUMPING_LEFT = 144, //lower tile pos
    UPDATE_PACKET_PLACE_BLOCK_RIGHT = 3104,
    UPDATE_PACKET_PLACE_BLOCK_LEFT = 3120,
    UPDATE_PACKET_PUNCH_TILE_RIGHT = 2592,
    UPDATE_PACKET_PUNCH_TILE_LEFT = 2608,
    UPDATE_PACKET_PICK_UP_OBJECT_RIGHT = 16416,
    UPDATE_PACKET_PICK_UP_OBJECT_LEFT = 16432
}