//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutonium.Agent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plutonium.Agent.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add_item\0\20\133\17\0\Blank\tiles_page1.rttex\91467596\0\-1\16\1\1\0\0\4\8\0\1\200\\0\400\\\\\0\0\0\0\255,255,255,255\255,255,255,255\0\0\0\\\\0\0\\0\0
        ///add_item\1\4\4\19\0\Blank Seed\tiles_page1.rttex\91467596\0\-1\16\1\1\0\0\20\2\0\1\200\\0\400\\\\\0\0\0\0\255,105,0,0\255,105,0,0\31\0\0\\\\0\0\\0\0
        ///add_item\2\0\0\17\0\Dirt\tiles_page1.rttex\91467596\0\-1\8\20\2\0\1\3\8\0\1\200\interface/large/store_buttons2.rttex\433625137\400\\\\\0\0\0\0\255,255,255,255\255,255,255,255\0\0\0\\\\0\0\\0\0
        ///add_item\3\0\0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemDefs {
            get {
                return ResourceManager.GetString("ItemDefs", resourceCulture);
            }
        }
    }
}
